name: NPCHirelingSystem
version: 1.0-SNAPSHOT
main: com.npchirelingsystem.NPCHirelingSystem
api-version: 1.20
authors: [Copilot]
description: A plugin for hiring and managing NPC workers.
depend: [Vault]

commands:
  hire:
    description: Main command for hiring NPCs
    usage: /hire <npc>
    permission: npchirelingsystem.hire
    aliases: [h]

permissions:
  npchirelingsystem.hire:
    description: Allows hiring NPCs
    default: true
