name: NPCHirelingSystem
version: 3.3
main: com.npchirelingsystem.NPCHirelingSystem
api-version: 1.20
authors: [KabiNSTR]
description: Плагин для найма и управления NPC-работниками.
depend: [Citizens]
softdepend: [Vault]

commands:
  hire:
    description: Основная команда для найма NPC
    usage: /hire <npc>
    permission: npchirelingsystem.hire
    aliases: [h]
  npcadmin:
    description: Админ-панель для управления NPC
    usage: /npcadmin [reload]
    permission: npchirelingsystem.admin
    aliases: [nadmin]
  contracts:
    description: Просмотр доступных торговых контрактов
    usage: /contracts
    aliases: [jobs, contract]

permissions:
  npchirelingsystem.hire:
    description: Позволяет нанимать NPC
    default: true
  npchirelingsystem.admin:
    description: Позволяет доступ к админ-панели и командам
    default: op
