name: NPCHirelingSystem
version: 2.6
main: com.npchirelingsystem.NPCHirelingSystem
api-version: 1.20
authors: [KabiNSTR]
description: A plugin for hiring and managing NPC workers.
softdepend: [Vault]

commands:
  hire:
    description: Main command for hiring NPCs
    usage: /hire <npc>
    permission: npchirelingsystem.hire
    aliases: [h]
  npcadmin:
    description: Admin panel for managing NPCs
    usage: /npcadmin [reload]
    permission: npchirelingsystem.admin
    aliases: [nadmin]
  contracts:
    description: View available trade contracts
    usage: /contracts
    aliases: [jobs, contract]

permissions:
  npchirelingsystem.hire:
    description: Allows hiring NPCs
    default: true
  npchirelingsystem.admin:
    description: Allows access to admin panel and commands
    default: op
